name: stroke_seg
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 2.0
  - torchvision
  - pytorch-cuda=12.1
  - pip
  - pip:
    - timm
    - diffusers
    - accelerate
  - scipy
  - matplotlib
  - pandas 
